import { readdir, readFile, writeFile, mkdir } from "node:fs/promises";
import { join, relative } from "node:path";
import chalk from "chalk";
import { parse as parseYaml } from "yaml";
import matter from "gray-matter";
import { findProjectRoot, safePath } from "../utils/paths.js";
import { loadConfig } from "../utils/config.js";
import { findFiles } from "../utils/fs.js";

interface DocsOptions {
  output?: string;
}

export async function generateDocs(options: DocsOptions): Promise<void> {
  const root = await findProjectRoot();
  const config = await loadConfig(root);

  const sections: string[] = [];

  // Title
  const projectName = await detectProjectName(root);
  sections.push(`# ${projectName}\n`);
  sections.push(
    `> Auto-generated by \`grimoire docs\` — ${new Date().toISOString().split("T")[0]}\n`
  );

  // 1. Project Summary
  const summary = buildProjectSummary(config);
  if (summary) sections.push(summary);

  // 2. System Architecture (from area docs)
  const architecture = await buildArchitectureSection(root);
  if (architecture) sections.push(architecture);

  // 3. Features
  const features = await buildFeaturesSection(root);
  if (features) sections.push(features);

  // 4. Data Model
  const dataModel = await buildDataModelSection(root);
  if (dataModel) sections.push(dataModel);

  // 5. Architecture Decisions
  const decisions = await buildDecisionsSection(root);
  if (decisions) sections.push(decisions);

  // 6. Recent Changes
  const changes = await buildChangesSection(root);
  if (changes) sections.push(changes);

  // 7. Active Work
  const active = await buildActiveSection(root);
  if (active) sections.push(active);

  const output = sections.join("\n---\n\n");

  const outputPath = options.output
    ? safePath(root, options.output)
    : join(root, ".grimoire", "docs", "OVERVIEW.md");
  await mkdir(join(root, ".grimoire", "docs"), { recursive: true });
  await writeFile(outputPath, output);

  console.log(chalk.green("Generated") + ` ${relative(root, outputPath)}`);
  console.log(
    chalk.dim(
      `  ${countSection(features, "feature")} · ${countSection(decisions, "decision")} · ${countSection(dataModel, "model")} · ${countSection(changes, "archived change")}`
    )
  );
}

function countSection(
  section: string | null,
  label: string
): string {
  if (!section) return `0 ${label}s`;
  // Count markdown headings at ### level as items
  const count = (section.match(/^### /gm) || []).length;
  return `${count} ${label}${count !== 1 ? "s" : ""}`;
}

// --- Project Summary ---

function buildProjectSummary(
  config: Awaited<ReturnType<typeof loadConfig>>
): string {
  const lines: string[] = ["## Project Summary\n"];

  const props: [string, string | undefined][] = [
    ["Language", config.project.language],
    ["Package Manager", config.project.package_manager],
    ["Commit Style", config.project.commit_style],
    ["Doc Tool", config.project.doc_tool],
    ["Comment Style", config.project.comment_style],
  ];

  const defined = props.filter(([, v]) => v);
  if (defined.length === 0) return "";

  lines.push("| Property | Value |");
  lines.push("|----------|-------|");
  for (const [key, val] of defined) {
    lines.push(`| ${key} | ${val} |`);
  }

  // Tools
  const toolEntries = Object.entries(config.tools);
  if (toolEntries.length > 0) {
    lines.push("");
    lines.push("**Configured Tools:**\n");
    lines.push("| Check | Tool | Command |");
    lines.push("|-------|------|---------|");
    for (const [check, tool] of toolEntries) {
      const cmd = tool.command ?? tool.check_command ?? (tool.name === "llm" ? "LLM review" : "—");
      lines.push(`| ${check} | ${tool.name} | \`${cmd}\` |`);
    }
  }

  lines.push("");
  return lines.join("\n");
}

// --- Architecture ---

async function buildArchitectureSection(
  root: string
): Promise<string | null> {
  const indexPath = join(root, ".grimoire", "docs", "index.yml");

  let indexContent: string;
  try {
    indexContent = await readFile(indexPath, "utf-8");
  } catch {
    return null;
  }

  const index = parseYaml(indexContent) as {
    areas?: Array<{
      name: string;
      path: string;
      directory: string;
      description: string;
    }>;
  };

  if (!index?.areas || index.areas.length === 0) return null;

  const lines: string[] = ["## System Architecture\n"];
  lines.push(
    "How the codebase is organized. Each area has a detailed doc in `.grimoire/docs/`.\n"
  );

  lines.push("| Area | Directory | Description |");
  lines.push("|------|-----------|-------------|");
  for (const area of index.areas) {
    lines.push(
      `| [${area.name}](${area.path}) | \`${area.directory}\` | ${area.description} |`
    );
  }

  // Try to read each area doc's Purpose section for a richer overview
  lines.push("");
  for (const area of index.areas) {
    const areaDoc = await safeRead(join(root, area.path));
    if (!areaDoc) continue;

    const purposeMatch = areaDoc.match(
      /^## Purpose\s*\n([\s\S]*?)(?=^## |\Z)/m
    );
    const boundariesMatch = areaDoc.match(
      /^## Boundaries\s*\n([\s\S]*?)(?=^## |\Z)/m
    );

    if (purposeMatch) {
      lines.push(`### ${area.name}\n`);
      lines.push(purposeMatch[1].trim());
      if (boundariesMatch) {
        lines.push("");
        lines.push(boundariesMatch[1].trim());
      }
      lines.push("");
    }
  }

  return lines.join("\n");
}

// --- Features ---

async function buildFeaturesSection(
  root: string
): Promise<string | null> {
  const featuresDir = join(root, "features");

  let featureFiles: string[];
  try {
    featureFiles = await findFiles(featuresDir, ".feature");
  } catch {
    return null;
  }

  if (featureFiles.length === 0) return null;

  const lines: string[] = ["## Features\n"];
  lines.push(
    "Behavioral specifications in Gherkin. Each scenario is an executable acceptance test.\n"
  );

  // Group by capability (first directory level)
  const byCapability = new Map<string, string[]>();
  for (const file of featureFiles) {
    const rel = relative(featuresDir, file);
    const capability = rel.includes("/") ? rel.split("/")[0] : "(root)";
    if (!byCapability.has(capability)) byCapability.set(capability, []);
    byCapability.get(capability)!.push(file);
  }

  for (const [capability, files] of byCapability) {
    lines.push(
      `### ${capability.charAt(0).toUpperCase() + capability.slice(1)}\n`
    );

    for (const file of files) {
      const content = await safeRead(file);
      if (!content) continue;

      const rel = relative(featuresDir, file);

      // Extract feature title and user story
      const titleMatch = content.match(/^Feature:\s*(.+)$/m);
      const title = titleMatch ? titleMatch[1].trim() : rel;

      const storyLines: string[] = [];
      const storyPattern = /^\s+(As an?|I want|So that)\s+(.+)$/gm;
      let m;
      while ((m = storyPattern.exec(content)) !== null) {
        storyLines.push(`${m[1]} ${m[2]}`);
      }

      lines.push(`**${title}** (\`features/${rel}\`)`);
      if (storyLines.length > 0) {
        lines.push(`> ${storyLines.join(" · ")}`);
      }
      lines.push("");

      // Extract scenarios
      const scenarios = content.match(
        /^\s*Scenario(?: Outline)?:\s*(.+)$/gm
      );
      if (scenarios) {
        for (const s of scenarios) {
          const name = s.replace(/^\s*Scenario(?: Outline)?:\s*/, "");
          lines.push(`- ${name}`);
        }
        lines.push("");
      }
    }
  }

  return lines.join("\n");
}

// --- Data Model ---

async function buildDataModelSection(
  root: string
): Promise<string | null> {
  const schemaPath = join(root, ".grimoire", "docs", "data", "schema.yml");

  let schemaContent: string;
  try {
    schemaContent = await readFile(schemaPath, "utf-8");
  } catch {
    return null;
  }

  const schema = parseYaml(schemaContent) as Record<
    string,
    Record<string, unknown>
  >;
  if (!schema || Object.keys(schema).length === 0) return null;

  const lines: string[] = ["## Data Model\n"];

  const internal: [string, Record<string, unknown>][] = [];
  const external: [string, Record<string, unknown>][] = [];

  for (const [name, def] of Object.entries(schema)) {
    if (!def || typeof def !== "object") continue;
    if (def.type === "external_api") {
      external.push([name, def]);
    } else {
      internal.push([name, def]);
    }
  }

  // Internal models
  if (internal.length > 0) {
    lines.push("### Internal Data\n");

    for (const [name, def] of internal) {
      const type = String(def.type ?? "table");
      const source = def.source ? ` — \`${def.source}\`` : "";
      const note = def.note ? ` — ${def.note}` : "";
      lines.push(`#### ${name} (${type})${source}${note}\n`);

      const fields = def.fields as
        | Record<string, Record<string, unknown>>
        | undefined;
      if (fields && typeof fields === "object") {
        lines.push("| Field | Type | Constraints |");
        lines.push("|-------|------|-------------|");
        for (const [fname, fdef] of Object.entries(fields)) {
          if (!fdef || typeof fdef !== "object") continue;
          const ftype = String(fdef.type ?? "unknown");
          const constraints: string[] = [];
          if (fdef.pk) constraints.push("PK");
          if (fdef.unique) constraints.push("unique");
          if (fdef.not_null) constraints.push("not null");
          if (fdef.default !== undefined)
            constraints.push(`default: ${fdef.default}`);
          if (fdef.ref) constraints.push(`→ ${fdef.ref}`);
          if (fdef.note) constraints.push(String(fdef.note));
          lines.push(
            `| ${fname} | ${ftype} | ${constraints.join(", ") || "—"} |`
          );
        }
        lines.push("");
      }

      const relationships = def.relationships as
        | Array<Record<string, string>>
        | undefined;
      if (relationships && Array.isArray(relationships)) {
        for (const rel of relationships) {
          lines.push(
            `- ${rel.type} → **${rel.target}** (via \`${rel.foreign_key ?? "?"}\`)`
          );
        }
        lines.push("");
      }
    }
  }

  // External APIs
  if (external.length > 0) {
    lines.push("### External APIs\n");

    for (const [name, def] of external) {
      const provider = def.provider ? ` (${def.provider})` : "";
      lines.push(`#### ${name}${provider}\n`);

      if (def.schema_ref) {
        lines.push(`- **Schema**: ${def.schema_ref}`);
      }
      if (def.client) {
        lines.push(`- **Client**: \`${def.client}\``);
      }
      if (def.auth) {
        lines.push(`- **Auth**: ${def.auth}`);
      }
      if (def.note) {
        lines.push(`- ${def.note}`);
      }

      const endpoints = def.endpoints as
        | Record<string, Record<string, unknown>>
        | undefined;
      if (endpoints && typeof endpoints === "object") {
        lines.push("");
        lines.push("| Endpoint | Method | Path |");
        lines.push("|----------|--------|------|");
        for (const [ename, edef] of Object.entries(endpoints)) {
          if (!edef || typeof edef !== "object") continue;
          const method = String(edef.method ?? edef.type ?? "—");
          const path = edef.path ? String(edef.path) : "—";
          lines.push(`| ${ename} | ${method} | \`${path}\` |`);
        }
      }
      lines.push("");
    }
  }

  return lines.join("\n");
}

// --- Decisions ---

async function buildDecisionsSection(
  root: string
): Promise<string | null> {
  const decisionsDir = join(root, ".grimoire", "decisions");

  let files: string[];
  try {
    const entries = await readdir(decisionsDir);
    files = entries
      .filter((f) => f.endsWith(".md") && f !== "template.md")
      .sort();
  } catch {
    return null;
  }

  if (files.length === 0) return null;

  const lines: string[] = ["## Architecture Decisions\n"];
  lines.push(
    "Key decisions recorded as MADR (Markdown Any Decision Records).\n"
  );

  lines.push("| # | Decision | Status | Date |");
  lines.push("|---|----------|--------|------|");

  for (const file of files) {
    const content = await safeRead(join(decisionsDir, file));
    if (!content) continue;

    // Extract frontmatter
    const { data: fm } = matter(content);
    const status = fm.status ? String(fm.status).trim() : "—";
    const date = fm.date ? String(fm.date).trim() : "—";

    // Extract title
    const titleMatch = content.match(/^#\s+(.+)$/m);
    const title = titleMatch ? titleMatch[1].trim() : file;

    const num = file.match(/^(\d+)/)?.[1] ?? "—";

    lines.push(
      `| ${num} | ${title} | ${status} | ${date} |`
    );
  }

  // Add detail sections for each decision
  lines.push("");
  for (const file of files) {
    const content = await safeRead(join(decisionsDir, file));
    if (!content) continue;

    const titleMatch = content.match(/^#\s+(.+)$/m);
    const title = titleMatch ? titleMatch[1].trim() : file;

    const contextMatch = content.match(
      /^## Context and Problem Statement\s*\n([\s\S]*?)(?=^## )/m
    );
    const outcomeMatch = content.match(
      /^## Decision Outcome\s*\n([\s\S]*?)(?=^## |^### Consequences)/m
    );

    lines.push(`### ${title}\n`);
    if (contextMatch) {
      lines.push(contextMatch[1].trim());
      lines.push("");
    }
    if (outcomeMatch) {
      lines.push(`**Outcome:** ${outcomeMatch[1].trim()}`);
      lines.push("");
    }
  }

  return lines.join("\n");
}

// --- Recent Changes ---

async function buildChangesSection(
  root: string
): Promise<string | null> {
  const archiveDir = join(root, ".grimoire", "archive");

  let dirs: string[];
  try {
    const entries = await readdir(archiveDir, { withFileTypes: true });
    dirs = entries
      .filter((d) => d.isDirectory())
      .map((d) => d.name)
      .sort()
      .reverse()
      .slice(0, 20); // Last 20
  } catch {
    return null;
  }

  if (dirs.length === 0) return null;

  const lines: string[] = ["## Recent Changes\n"];
  lines.push("Completed grimoire changes, newest first.\n");

  for (const dir of dirs) {
    const match = dir.match(/^(\d{4}-\d{2}-\d{2})-(.+)$/);
    if (!match) continue;

    const [, date, changeId] = match;
    const manifest = await safeRead(
      join(archiveDir, dir, "manifest.md")
    );
    if (!manifest) continue;

    const titleMatch = manifest.match(/^#\s+Change:\s*(.+)$/m);
    const summary = titleMatch ? titleMatch[1].trim() : changeId;

    const whyMatch = manifest.match(
      /^##\s+Why\s*\n([\s\S]*?)(?=^## |\Z)/m
    );
    const why = whyMatch ? whyMatch[1].trim() : "";

    lines.push(`### ${date} — ${summary}\n`);
    if (why) {
      lines.push(why);
      lines.push("");
    }
  }

  return lines.join("\n");
}

// --- Active Work ---

async function buildActiveSection(
  root: string
): Promise<string | null> {
  const changesDir = join(root, ".grimoire", "changes");

  let dirs: string[];
  try {
    const entries = await readdir(changesDir, { withFileTypes: true });
    dirs = entries.filter((d) => d.isDirectory()).map((d) => d.name);
  } catch {
    return null;
  }

  if (dirs.length === 0) return null;

  const lines: string[] = ["## Active Work\n"];
  lines.push("Changes currently in progress.\n");

  for (const dir of dirs) {
    const manifest = await safeRead(
      join(changesDir, dir, "manifest.md")
    );
    if (!manifest) continue;

    const titleMatch = manifest.match(/^#\s+Change:\s*(.+)$/m);
    const summary = titleMatch ? titleMatch[1].trim() : dir;

    // Extract status from frontmatter
    const { data: activeFm } = matter(manifest);
    const status = activeFm.status ? String(activeFm.status).trim() : "draft";

    // Check task progress
    let taskProgress = "";
    const tasks = await safeRead(join(changesDir, dir, "tasks.md"));
    if (tasks) {
      const done = (tasks.match(/^- \[x\] /gm) || []).length;
      const total =
        done + (tasks.match(/^- \[ \] /gm) || []).length;
      taskProgress = ` — ${done}/${total} tasks`;
    }

    lines.push(`- **${dir}**: ${summary} (${status}${taskProgress})`);
  }

  lines.push("");
  return lines.join("\n");
}

// --- Helpers ---

async function safeRead(path: string): Promise<string | null> {
  try {
    return await readFile(path, "utf-8");
  } catch {
    return null;
  }
}

// findFiles imported from utils/fs.js

async function detectProjectName(root: string): Promise<string> {
  // Try package.json
  try {
    const pkg = JSON.parse(
      await readFile(join(root, "package.json"), "utf-8")
    );
    if (pkg.name) return pkg.name;
  } catch {
    // ignore
  }

  // Try pyproject.toml
  try {
    const pyproject = await readFile(
      join(root, "pyproject.toml"),
      "utf-8"
    );
    const nameMatch = pyproject.match(/^name\s*=\s*"([^"]+)"/m);
    if (nameMatch) return nameMatch[1];
  } catch {
    // ignore
  }

  // Fall back to directory name
  return root.split("/").pop() ?? "Project";
}
