import { readdir, readFile, writeFile, mkdir } from "node:fs/promises";
import { join, relative, basename } from "node:path";
import chalk from "chalk";
import { parse as parseYaml } from "yaml";
import matter from "gray-matter";
import { findProjectRoot, safePath } from "../utils/paths.js";
import { loadConfig } from "../utils/config.js";
import { findFiles } from "../utils/fs.js";

interface DocsOptions {
  output?: string;
}

export async function generateDocs(options: DocsOptions): Promise<void> {
  const root = await findProjectRoot();
  const config = await loadConfig(root);

  const sections: string[] = [];

  // Title + byline as one header block (no separator between them).
  const projectName = await detectProjectName(root);
  sections.push(
    `# ${projectName}\n\n` +
      `> Auto-generated by \`grimoire docs\` — ${new Date().toISOString().split("T")[0]}.\n` +
      `> Portable CommonMark — include it in your doc tool; edit the source artifacts, not this file.`
  );

  // Fixed section order — the human entry point reads top to bottom:
  // what it is → capabilities → constraints → data → architecture → decisions.
  const summary = buildProjectSummary(config);
  if (summary) sections.push(summary);

  const features = await buildFeaturesSection(root);
  if (features) sections.push(features);

  const constraints = await buildConstraintsSection(root);
  if (constraints) sections.push(constraints);

  const dataModel = await buildDataModelSection(root);
  if (dataModel) sections.push(dataModel);

  const architecture = await buildArchitectureSection(root);
  if (architecture) sections.push(architecture);

  const decisions = await buildDecisionsSection(root);
  if (decisions) sections.push(decisions);

  // Active in-progress changes (read from .grimoire/changes/, not an archive).
  const active = await buildActiveSection(root);
  if (active) sections.push(active);

  // Blank-line-separated sections (CommonMark). No `---` thematic breaks —
  // they render as setext headings under preceding text in some parsers and
  // add noise when the file is included into another doc tool's tree.
  const output = sections.join("\n\n").trimEnd() + "\n";

  const outputPath = options.output
    ? safePath(root, options.output)
    : join(root, ".grimoire", "docs", "OVERVIEW.md");
  await mkdir(join(root, ".grimoire", "docs"), { recursive: true });
  await writeFile(outputPath, output);

  console.log(chalk.green("Generated") + ` ${relative(root, outputPath)}`);
  console.log(
    chalk.dim(
      `  ${countSection(features, "capability group")} · ${countSection(decisions, "decision")} · ${countSection(dataModel, "model")}`
    )
  );
}

function countSection(
  section: string | null,
  label: string
): string {
  if (!section) return `0 ${label}s`;
  // Count markdown headings at ### level as items
  const count = (section.match(/^### /gm) || []).length;
  return `${count} ${label}${count !== 1 ? "s" : ""}`;
}

// --- Project Summary ---

function buildProjectSummary(
  config: Awaited<ReturnType<typeof loadConfig>>
): string {
  const lines: string[] = ["## Project Summary\n"];

  const props: [string, string | undefined][] = [
    ["Language", config.project.language],
    ["Package Manager", config.project.package_manager],
    ["Commit Style", config.project.commit_style],
    ["Doc Tool", config.project.doc_tool],
    ["Comment Style", config.project.comment_style],
  ];

  const defined = props.filter(([, v]) => v);
  if (defined.length === 0) return "";

  lines.push("| Property | Value |");
  lines.push("|----------|-------|");
  for (const [key, val] of defined) {
    lines.push(`| ${key} | ${val} |`);
  }

  // Tools
  const toolEntries = Object.entries(config.tools);
  if (toolEntries.length > 0) {
    lines.push("");
    lines.push("**Configured Tools:**\n");
    lines.push("| Check | Tool | Command |");
    lines.push("|-------|------|---------|");
    for (const [check, tool] of toolEntries) {
      const cmd = tool.command ?? tool.check_command ?? (tool.name === "llm" ? "LLM review" : "—");
      lines.push(`| ${check} | ${tool.name} | \`${cmd}\` |`);
    }
  }

  lines.push("");
  return lines.join("\n");
}

// --- Architecture ---

async function buildArchitectureSection(
  root: string
): Promise<string | null> {
  const indexPath = join(root, ".grimoire", "docs", "index.yml");

  let indexContent: string;
  try {
    indexContent = await readFile(indexPath, "utf-8");
  } catch {
    return null;
  }

  const index = parseYaml(indexContent) as {
    areas?: Array<{
      name: string;
      path: string;
      directory: string;
      description: string;
    }>;
  };

  if (!index?.areas || index.areas.length === 0) return null;

  const lines: string[] = ["## System Architecture\n"];
  lines.push(
    "How the codebase is organized. Each area has a detailed doc in `.grimoire/docs/`.\n"
  );

  lines.push("| Area | Directory | Description |");
  lines.push("|------|-----------|-------------|");
  for (const area of index.areas) {
    lines.push(
      `| [${area.name}](${area.path}) | \`${area.directory}\` | ${area.description} |`
    );
  }

  // Try to read each area doc's Purpose section for a richer overview
  lines.push("");
  for (const area of index.areas) {
    const areaDoc = await safeRead(join(root, area.path));
    if (!areaDoc) continue;

    const purposeMatch = areaDoc.match(
      /^## Purpose\s*\n([\s\S]*?)(?=^## |\Z)/m
    );
    const boundariesMatch = areaDoc.match(
      /^## Boundaries\s*\n([\s\S]*?)(?=^## |\Z)/m
    );

    if (purposeMatch) {
      lines.push(`### ${area.name}\n`);
      lines.push(purposeMatch[1].trim());
      if (boundariesMatch) {
        lines.push("");
        lines.push(boundariesMatch[1].trim());
      }
      lines.push("");
    }
  }

  return lines.join("\n");
}

// --- Features ---

async function renderFeatureEntry(file: string, featuresDir: string): Promise<string[]> {
  const content = await safeRead(file);
  if (!content) return [];
  const rel = relative(featuresDir, file);
  const titleMatch = content.match(/^Feature:\s*(.+)$/m);
  const title = titleMatch ? titleMatch[1].trim() : rel;
  const storyLines: string[] = [];
  const storyPattern = /^\s+(As an?|I want|So that)\s+(.+)$/gm;
  let m;
  while ((m = storyPattern.exec(content)) !== null) {
    storyLines.push(`${m[1]} ${m[2]}`);
  }
  const lines: string[] = [];
  lines.push(`**${title}** (\`features/${rel}\`)`);
  if (storyLines.length > 0) lines.push(`> ${storyLines.join(" · ")}`);
  lines.push("");
  const scenarios = content.match(/^\s*Scenario(?: Outline)?:\s*(.+)$/gm);
  if (scenarios) {
    for (const s of scenarios) lines.push(`- ${s.replace(/^\s*Scenario(?: Outline)?:\s*/, "")}`);
    lines.push("");
  }
  return lines;
}

interface StoryMap {
  byFeature: Map<string, string>; // feature basename -> story title
  order: string[]; // story titles in declaration order
}

async function loadStories(root: string): Promise<StoryMap> {
  const byFeature = new Map<string, string>();
  const order: string[] = [];
  const content = await safeRead(join(root, ".grimoire", "docs", "index.yml"));
  if (!content) return { byFeature, order };

  const idx = parseYaml(content) as {
    stories?: Record<string, { title?: string; features?: string[] }>;
  };
  if (!idx?.stories) return { byFeature, order };

  for (const [key, story] of Object.entries(idx.stories)) {
    const title = story?.title ?? key;
    order.push(title);
    for (const f of story?.features ?? []) byFeature.set(f, title);
  }
  return { byFeature, order };
}

function titleCase(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

async function buildFeaturesSection(
  root: string
): Promise<string | null> {
  const featuresDir = join(root, "features");

  let featureFiles: string[];
  try {
    featureFiles = await findFiles(featuresDir, ".feature");
  } catch {
    return null;
  }

  if (featureFiles.length === 0) return null;

  const lines: string[] = ["## Capabilities\n"];
  lines.push("What the app does, for whom. Grouped by functional story; each scenario is an executable acceptance test.\n");

  // Group by functional story (from index.yml `stories:` map) when defined,
  // else fall back to the top-level feature directory as the group.
  const stories = await loadStories(root);
  const groups = new Map<string, string[]>();
  const fallbackOrder: string[] = [];
  for (const file of featureFiles) {
    const rel = relative(featuresDir, file);
    const base = basename(file, ".feature");
    const group =
      stories.byFeature.get(base) ??
      (rel.includes("/") ? rel.split("/")[0] : "(root)");
    if (!groups.has(group)) {
      groups.set(group, []);
      if (!stories.order.includes(group)) fallbackOrder.push(group);
    }
    groups.get(group)!.push(file);
  }

  const ordered = [
    ...stories.order.filter((t) => groups.has(t)),
    ...fallbackOrder,
  ];

  for (const group of ordered) {
    lines.push(`### ${titleCase(group)}\n`);
    for (const file of groups.get(group)!) {
      lines.push(...(await renderFeatureEntry(file, featuresDir)));
    }
  }

  return lines.join("\n");
}

async function buildConstraintsSection(
  root: string
): Promise<string | null> {
  const content = await safeRead(
    join(root, ".grimoire", "docs", "constraints.md")
  );
  if (!content) return null;

  // Pull real table rows — skip header, separator, and the _e.g._ template examples.
  const rows = content.split("\n").filter((line) => {
    const t = line.trim();
    return (
      t.startsWith("|") &&
      !t.startsWith("|--") &&
      !t.startsWith("|-") &&
      !/constraint \(assertion\)/i.test(t) &&
      !/_e\.g\._/.test(t)
    );
  });
  if (rows.length === 0) return null;

  return [
    "## Constraints\n",
    "Invariants that must always hold (security, NFRs, observability). Each is verified by a unit-invariant test, not a scenario.\n",
    "| Constraint | Rationale | Verified | Links |",
    "|------------|-----------|----------|-------|",
    ...rows,
  ].join("\n");
}

// --- Data Model ---

async function buildDataModelSection(
  root: string
): Promise<string | null> {
  const schemaPath = join(root, ".grimoire", "docs", "data", "schema.yml");

  let schemaContent: string;
  try {
    schemaContent = await readFile(schemaPath, "utf-8");
  } catch {
    return null;
  }

  const schema = parseYaml(schemaContent) as Record<
    string,
    Record<string, unknown>
  >;
  if (!schema || Object.keys(schema).length === 0) return null;

  const lines: string[] = ["## Data Model\n"];

  const internal: [string, Record<string, unknown>][] = [];
  const external: [string, Record<string, unknown>][] = [];

  for (const [name, def] of Object.entries(schema)) {
    if (!def || typeof def !== "object") continue;
    if (def.type === "external_api") {
      external.push([name, def]);
    } else {
      internal.push([name, def]);
    }
  }

  if (internal.length > 0) {
    lines.push("### Internal Data\n");
    lines.push(...renderInternalModels(internal));
  }

  if (external.length > 0) {
    lines.push("### External APIs\n");
    lines.push(...renderExternalApis(external));
  }

  return lines.join("\n");
}

function renderInternalModels(
  models: [string, Record<string, unknown>][]
): string[] {
  const lines: string[] = [];

  for (const [name, def] of models) {
    const type = String(def.type ?? "table");
    const source = def.source ? ` — \`${def.source}\`` : "";
    const note = def.note ? ` — ${def.note}` : "";
    lines.push(`#### ${name} (${type})${source}${note}\n`);

    const fields = def.fields as
      | Record<string, Record<string, unknown>>
      | undefined;
    if (fields && typeof fields === "object") {
      lines.push(...renderFieldsTable(fields));
    }

    const relationships = def.relationships as
      | Array<Record<string, string>>
      | undefined;
    if (relationships && Array.isArray(relationships)) {
      lines.push(...renderRelationships(relationships));
    }
  }

  return lines;
}

function renderEndpointsTable(
  endpoints: Record<string, Record<string, unknown>>
): string[] {
  const lines: string[] = ["", "| Endpoint | Method | Path |", "|----------|--------|------|"];
  for (const [ename, edef] of Object.entries(endpoints)) {
    if (!edef || typeof edef !== "object") continue;
    const method = String(edef.method ?? edef.type ?? "—");
    const path = edef.path ? String(edef.path) : "—";
    lines.push(`| ${ename} | ${method} | \`${path}\` |`);
  }
  return lines;
}

function renderExternalApis(
  apis: [string, Record<string, unknown>][]
): string[] {
  const lines: string[] = [];

  for (const [name, def] of apis) {
    const provider = def.provider ? ` (${def.provider})` : "";
    lines.push(`#### ${name}${provider}\n`);

    if (def.schema_ref) lines.push(`- **Schema**: ${def.schema_ref}`);
    if (def.client) lines.push(`- **Client**: \`${def.client}\``);
    if (def.auth) lines.push(`- **Auth**: ${def.auth}`);
    if (def.note) lines.push(`- ${def.note}`);

    const endpoints = def.endpoints as Record<string, Record<string, unknown>> | undefined;
    if (endpoints && typeof endpoints === "object") {
      lines.push(...renderEndpointsTable(endpoints));
    }
    lines.push("");
  }

  return lines;
}

function buildFieldConstraints(fdef: Record<string, unknown>): string {
  const constraints: string[] = [];
  if (fdef.pk) constraints.push("PK");
  if (fdef.unique) constraints.push("unique");
  if (fdef.not_null) constraints.push("not null");
  if (fdef.default !== undefined) constraints.push(`default: ${fdef.default}`);
  if (fdef.ref) constraints.push(`→ ${fdef.ref}`);
  if (fdef.note) constraints.push(String(fdef.note));
  return constraints.join(", ") || "—";
}

function renderFieldsTable(
  fields: Record<string, Record<string, unknown>>
): string[] {
  const lines: string[] = ["| Field | Type | Constraints |", "|-------|------|-------------|"];
  for (const [fname, fdef] of Object.entries(fields)) {
    if (!fdef || typeof fdef !== "object") continue;
    const ftype = String(fdef.type ?? "unknown");
    lines.push(`| ${fname} | ${ftype} | ${buildFieldConstraints(fdef)} |`);
  }
  lines.push("");
  return lines;
}

function renderRelationships(
  relationships: Array<Record<string, string>>
): string[] {
  const lines: string[] = [];

  for (const rel of relationships) {
    lines.push(
      `- ${rel.type} → **${rel.target}** (via \`${rel.foreign_key ?? "?"}\`)`
    );
  }
  lines.push("");

  return lines;
}

// --- Decisions ---

function isSuperseded(content: string): boolean {
  const { data: fm } = matter(content);
  return fm.status ? String(fm.status).toLowerCase().includes("superseded") : false;
}

async function renderDecisionRow(file: string, decisionsDir: string): Promise<string | null> {
  const content = await safeRead(join(decisionsDir, file));
  if (!content) return null;
  if (isSuperseded(content)) return null; // OVERVIEW shows current decisions only
  const { data: fm } = matter(content);
  const status = fm.status ? String(fm.status).trim() : "—";
  const date = fm.date ? String(fm.date).trim() : "—";
  const titleMatch = content.match(/^#\s+(.+)$/m);
  const title = titleMatch ? titleMatch[1].trim() : file;
  const num = file.match(/^(\d+)/)?.[1] ?? "—";
  return `| ${num} | ${title} | ${status} | ${date} |`;
}

async function renderDecisionDetail(file: string, decisionsDir: string): Promise<string[] | null> {
  const content = await safeRead(join(decisionsDir, file));
  if (!content) return null;
  if (isSuperseded(content)) return null;
  const titleMatch = content.match(/^#\s+(.+)$/m);
  const title = titleMatch ? titleMatch[1].trim() : file;
  const contextMatch = content.match(/^## Context and Problem Statement\s*\n([\s\S]*?)(?=^## )/m);
  const outcomeMatch = content.match(/^## Decision Outcome\s*\n([\s\S]*?)(?=^## |^### Consequences)/m);
  const lines: string[] = [`### ${title}\n`];
  if (contextMatch) { lines.push(contextMatch[1].trim()); lines.push(""); }
  if (outcomeMatch) { lines.push(`**Outcome:** ${outcomeMatch[1].trim()}`); lines.push(""); }
  return lines;
}

async function buildDecisionsSection(
  root: string
): Promise<string | null> {
  const decisionsDir = join(root, ".grimoire", "decisions");

  let files: string[];
  try {
    const entries = await readdir(decisionsDir);
    files = entries.filter((f) => f.endsWith(".md") && f !== "template.md").sort();
  } catch {
    return null;
  }

  if (files.length === 0) return null;

  const lines: string[] = [
    "## Architecture Decisions\n",
    "Key decisions recorded as MADR (Markdown Any Decision Records).\n",
    "| # | Decision | Status | Date |",
    "|---|----------|--------|------|",
  ];

  for (const file of files) {
    const row = await renderDecisionRow(file, decisionsDir);
    if (row) lines.push(row);
  }

  lines.push("");
  for (const file of files) {
    const detail = await renderDecisionDetail(file, decisionsDir);
    if (detail) lines.push(...detail);
  }

  return lines.join("\n");
}

// Completed-change history is git, not an archive tree — `git log --grep
// "Change: <id>"` and the PR are the record. No buildChangesSection here.

// --- Active Work ---

async function buildActiveSection(
  root: string
): Promise<string | null> {
  const changesDir = join(root, ".grimoire", "changes");

  let dirs: string[];
  try {
    const entries = await readdir(changesDir, { withFileTypes: true });
    dirs = entries.filter((d) => d.isDirectory()).map((d) => d.name);
  } catch {
    return null;
  }

  if (dirs.length === 0) return null;

  const lines: string[] = ["## Active Work\n"];
  lines.push("Changes currently in progress.\n");

  for (const dir of dirs) {
    const manifest = await safeRead(
      join(changesDir, dir, "manifest.md")
    );
    if (!manifest) continue;

    const titleMatch = manifest.match(/^#\s+Change:\s*(.+)$/m);
    const summary = titleMatch ? titleMatch[1].trim() : dir;

    // Extract status from frontmatter
    const { data: activeFm } = matter(manifest);
    const status = activeFm.status ? String(activeFm.status).trim() : "draft";

    // Check task progress
    let taskProgress = "";
    const tasks = await safeRead(join(changesDir, dir, "tasks.md"));
    if (tasks) {
      const done = (tasks.match(/^- \[x\] /gm) || []).length;
      const total =
        done + (tasks.match(/^- \[ \] /gm) || []).length;
      taskProgress = ` — ${done}/${total} tasks`;
    }

    lines.push(`- **${dir}**: ${summary} (${status}${taskProgress})`);
  }

  lines.push("");
  return lines.join("\n");
}

// --- Helpers ---

async function safeRead(path: string): Promise<string | null> {
  try {
    return await readFile(path, "utf-8");
  } catch {
    return null;
  }
}

// findFiles imported from utils/fs.js

async function detectProjectName(root: string): Promise<string> {
  // Try package.json
  try {
    const pkg = JSON.parse(
      await readFile(join(root, "package.json"), "utf-8")
    );
    if (pkg.name) return pkg.name;
  } catch {
    // ignore
  }

  // Try pyproject.toml
  try {
    const pyproject = await readFile(
      join(root, "pyproject.toml"),
      "utf-8"
    );
    const nameMatch = pyproject.match(/^name\s*=\s*"([^"]+)"/m);
    if (nameMatch) return nameMatch[1];
  } catch {
    // ignore
  }

  // Fall back to directory name
  return root.split("/").pop() ?? "Project";
}
