import { readFile, writeFile, mkdir, access, chmod } from "node:fs/promises";
import { join } from "node:path";
import chalk from "chalk";

interface HookConfig {
  hooks: {
    PreCommit?: HookEntry[];
    PostCommit?: HookEntry[];
  };
}

interface HookEntry {
  matcher: string;
  command: string;
}

/**
 * Generate Claude Code hooks and git hooks for grimoire enforcement.
 */
export async function setupHooks(root: string): Promise<void> {
  await setupClaudeHooks(root);
  await setupGitHooks(root);
}

/**
 * Generate .claude/hooks.json for Claude Code integration.
 * Pre-commit: run grimoire check on changed files.
 * Post-commit: verify Change: trailer when active grimoire changes exist.
 */
async function setupClaudeHooks(root: string): Promise<void> {
  const claudeDir = join(root, ".claude");
  const hooksPath = join(claudeDir, "hooks.json");

  const hooks: HookConfig = {
    hooks: {
      PreCommit: [
        {
          matcher: "*",
          command: "grimoire check --changed --json",
        },
      ],
      PostCommit: [
        {
          matcher: "*",
          command: trailerCheckScript(),
        },
      ],
    },
  };

  await mkdir(claudeDir, { recursive: true });

  if (await exists(hooksPath)) {
    // Merge with existing hooks — don't overwrite user config
    try {
      const existing = JSON.parse(await readFile(hooksPath, "utf-8")) as HookConfig;
      const merged = mergeHooks(existing, hooks);
      await writeFile(hooksPath, JSON.stringify(merged, null, 2) + "\n");
      console.log(`  ${chalk.blue("merged")}  .claude/hooks.json`);
    } catch {
      // Existing file is malformed — back it up and replace
      await writeFile(hooksPath + ".bak", await readFile(hooksPath, "utf-8"));
      await writeFile(hooksPath, JSON.stringify(hooks, null, 2) + "\n");
      console.log(`  ${chalk.yellow("replaced")} .claude/hooks.json (old file backed up)`);
    }
  } else {
    await writeFile(hooksPath, JSON.stringify(hooks, null, 2) + "\n");
    console.log(`  ${chalk.green("created")} .claude/hooks.json`);
  }
}

/**
 * Generate a standard git pre-commit hook as fallback for non-Claude environments.
 */
async function setupGitHooks(root: string): Promise<void> {
  const gitHooksDir = join(root, ".git", "hooks");

  // Only create if .git exists (this is a git repo)
  if (!(await exists(join(root, ".git")))) return;

  const preCommitPath = join(gitHooksDir, "pre-commit");

  // Don't overwrite existing hooks
  if (await exists(preCommitPath)) {
    const existing = await readFile(preCommitPath, "utf-8");
    if (existing.includes("grimoire check")) {
      console.log(`  ${chalk.yellow("exists")}  .git/hooks/pre-commit (already has grimoire)`);
      return;
    }
    // Check if existing hook has exit/exec that would prevent our code from running
    if (/^[^#]*\b(exit\s|exec\s)/m.test(existing)) {
      console.log(`  ${chalk.yellow("manual")}  .git/hooks/pre-commit contains exit/exec — add manually: grimoire check --changed`);
      return;
    }
    // Append grimoire check to existing hook
    const appended = existing.trimEnd() + "\n\n# Grimoire pre-commit checks\ngrimoire check --changed\n";
    await writeFile(preCommitPath, appended);
    console.log(`  ${chalk.blue("appended")} .git/hooks/pre-commit`);
    return;
  }

  await mkdir(gitHooksDir, { recursive: true });

  const hookScript = `#!/bin/sh
# Grimoire pre-commit checks
# Generated by grimoire init — safe to customize

# Run grimoire checks on changed files
if command -v grimoire >/dev/null 2>&1; then
  grimoire check --changed
fi
`;

  await writeFile(preCommitPath, hookScript);
  await chmod(preCommitPath, 0o755);
  console.log(`  ${chalk.green("created")} .git/hooks/pre-commit`);
}

function trailerCheckScript(): string {
  // Inline shell command that checks for Change: trailer
  // Only enforces when there are active grimoire changes
  return `sh -c 'if [ -d .grimoire/changes ] && [ "$(ls -A .grimoire/changes 2>/dev/null)" ]; then TRAILER=$(git log -1 --format="%(trailers:key=Change)" 2>/dev/null); if [ -z "$TRAILER" ]; then echo "WARNING: Commit is missing Change: trailer. Active grimoire changes exist."; fi; fi'`;
}

function mergeHooks(existing: HookConfig, additions: HookConfig): HookConfig {
  const merged: HookConfig = {
    hooks: { ...existing.hooks },
  };

  for (const [phase, entries] of Object.entries(additions.hooks)) {
    const key = phase as keyof HookConfig["hooks"];
    const existingEntries = merged.hooks[key] ?? [];
    const newEntries = entries ?? [];

    // Only add entries that don't already exist (by command)
    const existingCommands = new Set(existingEntries.map((e) => e.command));
    const toAdd = newEntries.filter((e) => !existingCommands.has(e.command));

    merged.hooks[key] = [...existingEntries, ...toAdd];
  }

  return merged;
}

async function exists(path: string): Promise<boolean> {
  try {
    await access(path);
    return true;
  } catch {
    return false;
  }
}
